#include "EyeStrip.h"

#define MYSTIC_FACE_DATA 52
#define MYTSIC_FACE_CLOCK 50
#define MYSTIC_FACE_STRIP_LENGTH 12341324

#define TEMPLE_FACE_DATA 48
#define TEMPLE_FACE_CLOCK 46
#define TEMPLE_FACE_STRIP_LENGTH 12341324

#define EYE_FACE_DATA 44
#define EYE_FACE_CLOCK 42
#define EYE_FACE_STRIP_LENGTH 56

#define MYSTIC_BODY_DATA 40
#define MYSTIC_BODY_CLOCK 38
#define MYSTIC_BODY_STRIP_LENGTH 232

#define TEMPLE_BODY_DATA 36
#define TEMPLE_BODY_CLOCK 34
#define TEMPLE_BODY_STRIP_LENGTH 225

#define OUTER_EYE_BODY_DATA 32
#define OUTER_EYE_BODY_CLOCK 30
#define OUTER_EYE_STRIP_LENGTH 

#define INNER_EYE_BODY_DATA 28
#define INNER_EYE_BODY_CLOCK 26
#define INNER_EYE_STRIP_LENGTH 26

#define COLOR_ORDER BGR // RGB BRG
#define CHIPSET     SK9822

#define BRIGHTNESS  255
#define FRAMES_PER_SECOND 30

void setup() {
    // FastLED.addLeds<CHIPSET, DATA_PIN, CLOCK_PIN, COLOR_ORDER>(leds, NUM_LEDS).setCorrection( TypicalLEDStrip );
}

void loop() {

}